In [1]:
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Model
from keras import models 
from keras.layers import Dropout, Input,Dense
from keras.utils import to_categorical
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

In [2]:
iris = load_iris()

In [3]:
df = pd.DataFrame(iris.data,columns = iris.feature_names)
df["species"]=iris.target

In [4]:
X = iris.data
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
X_train,X_test,y_train,y_test = train_test_split(
    X,y,
    test_size = 0.2,
    random_state = 42
)

In [7]:
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

In [8]:
y_train

array([0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2,
       1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1,
       0, 0, 2, 2, 0, 0, 0, 1, 2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 2, 0, 1, 2, 0, 1, 2])

In [9]:
num_digit = 3
#Oe_Hot Encoding
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [10]:
model = models.Sequential()
model.add(Input(shape=(4,)))
model.add(Dense(16,activation = "relu"))
model.add(Dropout(0.25))
model.add(Dense(8,activation = "relu"))
model.add(Dropout(0.20))
model.add(Dense(3,activation='softmax'))

In [11]:
model.compile(
    optimizer = "SGD",
    loss = "categorical_crossentropy",
    metrics = ["accuracy"]
)

In [15]:
model.fit( X_train,y_train, batch_size = 100, epochs = 20, verbose = 2, validation_data = (X_test,y_test)
)

Epoch 1/20
2/2 - 0s - 67ms/step - accuracy: 0.4750 - loss: 1.0332 - val_accuracy: 0.4000 - val_loss: 1.0079
Epoch 2/20
2/2 - 0s - 50ms/step - accuracy: 0.4000 - loss: 1.0237 - val_accuracy: 0.4000 - val_loss: 1.0038
Epoch 3/20
2/2 - 0s - 48ms/step - accuracy: 0.4500 - loss: 1.0449 - val_accuracy: 0.4000 - val_loss: 0.9993
Epoch 4/20
2/2 - 0s - 46ms/step - accuracy: 0.4333 - loss: 1.0157 - val_accuracy: 0.4000 - val_loss: 0.9945
Epoch 5/20
2/2 - 0s - 48ms/step - accuracy: 0.4250 - loss: 1.0191 - val_accuracy: 0.4333 - val_loss: 0.9896
Epoch 6/20
2/2 - 0s - 46ms/step - accuracy: 0.4833 - loss: 1.0042 - val_accuracy: 0.4333 - val_loss: 0.9851
Epoch 7/20
2/2 - 0s - 46ms/step - accuracy: 0.4417 - loss: 1.0022 - val_accuracy: 0.4333 - val_loss: 0.9810
Epoch 8/20
2/2 - 0s - 47ms/step - accuracy: 0.5000 - loss: 1.0142 - val_accuracy: 0.5000 - val_loss: 0.9770
Epoch 9/20
2/2 - 0s - 46ms/step - accuracy: 0.4500 - loss: 1.0130 - val_accuracy: 0.5000 - val_loss: 0.9726
Epoch 10/20
2/2 - 0s - 47ms/

In [13]:
print(X_train[:5])

[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]]


In [14]:
print(y_train.shape)
print(y_train[:5])

(120, 3)
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
